In [1]:
# notebooks/test_model_fit.ipynb

# 0. Add root folder (parent of src/) to path
import sys
from pathlib import Path

# Adiciona a raiz do projeto ao path (um nível acima da pasta notebooks/)
root_dir = Path("..").resolve()
sys.path.append(str(root_dir))

# 1. Imports
from src.data_processing import load_and_process_data  # <- nome correto da função
from src.model_fit import fit_all_models

# 2. Paths
data_file = root_dir / "data" / "raw" / "DurangoDataR.txt"
output_file = root_dir / "results" / "model_fit_summary_numeric.csv"

# 3. Load data
df = load_and_process_data(data_file)  # <- função correta
display(df.head())

# 4. Fit models
results_df = fit_all_models(df)

# 5. Show output
display(results_df)

   tempoS  temperK      r    e.r    rho  e.rho
0    3600   398.15  0.993  0.004  0.993  0.004
1    3600   423.15  0.989  0.004  0.989  0.004
2    3600   423.15  0.990  0.004  0.990  0.004
3    3600   448.15  0.979  0.004  0.979  0.004
4    3600   449.15  0.979  0.004  0.979  0.004

,model,params,errors,r_squared,chi_squared,reduced_chi_squared
0,PA,"[6.843675784300511, 0.2187629261179567, -12.08...","[0.0901712562123878, 0.002666930847111326, 0.1...",0.961934,960.183185,16.274291
1,PC,"[-5.289972397546014, 0.22403051582225636, -11....","[0.04057452357721021, 0.0026946738408807434, 0...",0.965579,792.818981,13.437610
2,FA,"[-7.0283800439540265, 0.1024731246355417, -9.4...","[0.2203404640071071, 0.003990059808798249, 1.0...",0.979405,462.044655,7.966287
3,FC,"[-9.01576733657535, 0.15530154317107392, -17.4...","[0.42221310046012644, 0.008530150366820487, 1....",0.975760,522.209229,9.003607